###GET HOME
GET http://localhost:8100/api
Content-Type: application/json

###GET ALL PRODUCTS
GET http://localhost:8100/api/products
Content-Type: application/json

{}

###POST
POST http://localhost:8100/api/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10.1
}

###POST
POST http://localhost:8100/api/products
Content-Type: application/json

{
    "name": "Product 2",
    "price": 20.2
}

###PUT
PUT http://localhost:8100/api/products/1
Content-Type: application/json

{
    "name": "Product 1 updated",
    "price": 11.1
}

###DELETE
DELETE http://localhost:8100/api/products/1
Content-Type: application/json



###GET ALL PRODUCTS SERVER
GET http://springboot.alwaysdata.net/api/products
Content-Type: application/json

{}

###POST
POST http://springboot.alwaysdata.net/api/products
Content-Type: application/json

{
    "name": "Product 1",
    "price": 10.1
}