DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    PRICE DOUBLE NOT NULL
);

INSERT INTO PRODUCTS (NAME, PRICE) VALUES 
    ('Laptop', 999.99),
    ('Smartphone', 699.99),
    ('Headphones', 199.99);
